Feature/step 2
skoomer/bookstore pull request #2
Opened 2021-04-22 09:28 UTC by skoomer

2 step
	•	Catalog;
	•	Show books
	•	Show categories with books count
	•	Filter/Sort books
	•	Paginate books 
Except bestseller logic and images
	•	Book page
	•	Info about book
	•	Price calculator
	•	Read more
	•	Back to results Without images; Without reviews; Without Add to Cart functionality
	•	Write tests (unit, feature) for your new code.

heroku 

https://thawing-dusk-89266.herokuapp.com/

2021-04-27 07:50 UTC, AnastasiaBortnovska requested changes

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on app/controllers/books_controller.rb
> +  BOOKS_TRUNCATE = SHORT_TRUNCATE + 1
```suggestion
  BOOKS_TRUNCATE = SHORT_TRUNCATE.next
```

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on app/queries/books/find_books.rb
> +      @books = books
```suggestion
    def initialize(params)
      @books = Book.all
```

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on app/views/pages/index.html.haml
> +                                %p.lead.small= book.author.first_name
move to decorator

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on spec/controllers/books_controller_spec.rb
> +require 'pry'
remove

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on spec/factories/book.rb
> +    end
Do you need it?

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on spec/features/book_page_detail_spec.rb
> +RSpec.describe 'BookDetail', type: :feature do
```suggestion
RSpec.describe 'BookDetail' do
```

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on spec/features/book_page_detail_spec.rb
> +  let(:book_material) { ['leather', 'glossy paper', 'matte paper'] }
use ffaker

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on spec/features/book_page_spec.rb
> +RSpec.describe 'BookPage', type: :feature do
```suggestion
RSpec.describe 'BookPage' do
```

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on spec/features/book_page_detail_spec.rb
> +  let(:category) { FactoryBot.create(:category) }
you can just write let!(:book) { create(:book) }

2021-04-27 07:50 UTC, AnastasiaBortnovska commented on spec/support/config/simplecov.rb
> +  minimum_coverage 90
```suggestion
  minimum_coverage 95
```

2021-04-27 20:06 UTC, AnastasiaBortnovska approved these changes

2021-04-28 11:58 UTC, OlexandrToloshnyak approved these changes

2021-05-04 12:46 UTC, legendado requested changes

2021-05-04 12:46 UTC, legendado commented on .rubocop.yml
> +  Enabled: false
Why disabled?

2021-05-04 12:46 UTC, legendado commented on app/assets/stylesheets/books.scss
> +// Place all the styles related to the books controller here.
It can be removed

2021-05-04 12:46 UTC, legendado commented on app/assets/stylesheets/categories.scss
> +// Place all the styles related to the Categories controller here.
It can be removed

2021-05-04 12:46 UTC, legendado commented on app/controllers/books_controller.rb
> +    @books_count = Book.all.count
```suggestion
    @books_count = Book.count
```

2021-05-04 12:46 UTC, legendado commented on app/controllers/books_controller.rb
> +    Pagy::VARS[:max_items] = BOOKS_ON_PAGE
Move it to global config

2021-05-04 12:46 UTC, legendado commented on app/controllers/books_controller.rb
> +    @pagy, @books = pagy_countless(scoped_books, items: BOOKS_ON_PAGE, link_extra: 'data-remote="true"')
Do you redefine here items count?
```suggestion
    @pagy, @books = pagy_countless(scoped_books, link_extra: 'data-remote="true"')
```

2021-05-04 12:46 UTC, legendado commented on app/controllers/books_controller.rb
> +      format.js
Are you sure that you need `json` format here?

2021-05-04 12:46 UTC, legendado commented on app/decorators/book_decorator.rb
> +  TRUNCATE = 240
Could we use another name?

2021-05-04 12:46 UTC, legendado commented on app/decorators/book_decorator.rb
> +    "H: #{height}\" x W: #{width}\" x D: #{depth}"
Move it to i18n
Height, width, depth could be translated

2021-05-04 12:46 UTC, legendado commented on app/controllers/books_controller.rb
> +  include Filtering
Why do you need it here?

2021-05-04 12:46 UTC, legendado commented on app/models/author.rb
> +class Author < ApplicationRecord
Following specs the model validation is absent

2021-05-04 12:46 UTC, legendado commented on app/models/book.rb
> +class Book < ApplicationRecord
Following specs the model validation is absent

2021-05-04 12:46 UTC, legendado commented on app/models/category.rb
> +class Category < ApplicationRecord
Following specs the model validation is absent

2021-05-04 12:46 UTC, legendado commented on app/models/concerns/filtering.rb
> +  BOOK_FILTERING_ORDER = {
I think it should be the part of query object

2021-05-04 12:46 UTC, legendado commented on app/models/concerns/filtering.rb
> +    'price DESC' => 'Price: High to low'
`Title A-Z`, etc could be translated, so move it to i18n

2021-05-04 12:46 UTC, legendado commented on app/queries/books/find_books.rb
> +      @books = Book.all
It is not good idea to initialize it every call of filter
Remove it

2021-05-04 12:46 UTC, legendado commented on app/queries/books/find_books.rb
> +  class FindBooks
Follow the naming guideline
```suggestion
  class FilterQuery
```

2021-05-04 12:46 UTC, legendado commented on app/queries/books/find_books.rb
> +  class FindBooks
And rename the file

2021-05-04 12:46 UTC, legendado commented on app/queries/books/find_books.rb
> +      @sort_by_param ? select_books.order(@sort_by_param) : select_books.order(DEFAULT_SORT)
There is possible SQL injection in `.order(@sort_by_param)`
Use your filtering constant to validate order parameter

2021-05-04 12:46 UTC, legendado commented on app/queries/books/find_books.rb
> +      select_books = @category_id ? Category.find(@category_id).books : @books
Avoid using of `find` method if your method not marked as dangerous

2021-05-04 12:46 UTC, legendado commented on app/queries/books/find_books.rb
> +      select_books = @category_id ? Category.find(@category_id).books : @books
Propose to use `yield_self` for filtering and order

2021-05-04 12:46 UTC, legendado commented on app/views/books/index.haml
> +      -if (pagy_next_url(@pagy))
```suggestion
      - if pagy_next_url(@pagy)
```

2021-05-04 12:46 UTC, legendado commented on app/views/books/partials/_book.haml
> +            = t('.price', price: book.price)
Why do you need i18n here?
Use `number_to_currency` helper instead

2021-05-04 12:46 UTC, legendado commented on app/views/books/partials/_book.haml
> +        %p.lead.small= book.author.first_name
Why only first_name?
Use decorator method instead

2021-05-04 12:46 UTC, legendado commented on app/views/books/partials/_filter.haml
> +          = params[:sort_by]? Filtering::BOOK_FILTERING_ORDER[params[:sort_by]] : Filtering::BOOK_FILTERING_ORDER.first[1]
What is `first[1]`?
Simplify it

2021-05-04 12:46 UTC, legendado commented on app/views/books/partials/_filter.haml
> +          = params[:sort_by]? Filtering::BOOK_FILTERING_ORDER[params[:sort_by]] : Filtering::BOOK_FILTERING_ORDER.first[1]
What if `sort_by` parameter will not exists in `BOOK_FILTERING_ORDER`?

2021-05-04 12:46 UTC, legendado commented on app/views/books/partials/_filter.haml
> +      - Category.all.each do |category|
Move it to controller

2021-05-04 12:46 UTC, legendado commented on app/views/books/partials/_next_page_link.haml
> += link_to t('.button'), pagy_next_url(@pagy), class: 'btn btn-primary',remote: true, id:'next_link'
```suggestion
= link_to t('.button'), pagy_next_url(@pagy), class: 'btn btn-primary', remote: true, id: 'next_link'
```

2021-05-04 12:46 UTC, legendado commented on app/views/books/partials/_filter.haml
> +          = params[:sort_by]? Filtering::BOOK_FILTERING_ORDER[params[:sort_by]] : Filtering::BOOK_FILTERING_ORDER.first[1]
```suggestion
          = params[:sort_by] ? Filtering::BOOK_FILTERING_ORDER[params[:sort_by]] : Filtering::BOOK_FILTERING_ORDER.first[1]
```

2021-05-04 12:46 UTC, legendado commented on app/views/books/show.haml
> +      %h1.mt-res-0= @book.title
Avoid using the instance variables on partials
```suggestion
      %h1.mt-res-0= book.title
```

2021-05-04 12:46 UTC, legendado commented on app/views/books/show.haml
> +          %p.h1.in-gold-500.mt-10= t('.price', price: @book.price)
Use `number_to_currency` helper

2021-05-04 12:46 UTC, legendado commented on app/views/books/show.haml
> +          = button_tag t('.buttons.read_more'), disabled: book.description_truncate?, class: 'btn-link in-gold-500 ml-10 read-more-js'
So, this button are always display?

2021-05-04 12:46 UTC, legendado commented on app/views/books/show.haml
> +            = @book.publication_year
```suggestion
            = book.publication_year
```

2021-05-04 12:46 UTC, legendado commented on app/views/error/404.html
> +<!DOCTYPE html>
Rename folder to `errors`

2021-05-04 12:46 UTC, legendado commented on app/views/partials/_header.haml
> +              - Category.all.each do |category|
Don't use query to database in views

2021-05-04 12:46 UTC, legendado commented on app/views/partials/_header.haml
> +              - Category.all.each do |category|
Don't use query to database in views

2021-05-04 12:46 UTC, legendado commented on config/locales/books.yml
> +      price: "€%{price}"
Remove it
Use `number_to_currency` helper instead

2021-05-04 12:46 UTC, legendado commented on config/locales/books.yml
> +        price: "€%{price}"
The same

2021-05-04 12:46 UTC, legendado commented on config/locales/books.yml
> +
Remove empty line

2021-05-04 12:46 UTC, legendado commented on config/routes.rb
> +  resources :books, only:[:index, :show]
```suggestion
  resources :books, only: %i[index show]
```

2021-05-04 12:46 UTC, legendado commented on config/routes.rb
> +
Remove empty line

2021-05-04 12:46 UTC, legendado commented on db/migrate/20210415092643_create_categories.rb
> +      t.string :title, null: false, unique: true
The database structure does not match the structure of models

2021-05-04 12:46 UTC, legendado commented on db/migrate/20210423150023_reset_all_book_cacha_counters.rb
> +    Category.all.each do |category|
```suggestion
    Category.find_each do |category|
```

2021-05-04 12:46 UTC, legendado commented on db/seeds.rb
> +    publication_year: rand(2000...Time.zone.now.year) ,
```suggestion
    publication_year: rand(2000...Time.zone.now.year),
```

2021-05-04 12:46 UTC, legendado commented on db/seeds.rb
> +    category_id: Category.all.sample.id,
```suggestion
    category: Category.sample,
```

2021-05-04 12:46 UTC, legendado commented on db/seeds.rb
> +    author_id: Author.all.sample.id
```suggestion
    author: Author.sample
```

2021-05-04 12:46 UTC, legendado commented on db/seeds.rb
> +
Remove empty line

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +    it 'return http success' do
```suggestion
    it 'returns http success' do
```

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +    it 'render index template' do
```suggestion
    it 'renders index template' do
```

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +  describe 'assingns' do
Move this describe to index tests

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +  describe 'GET /index' do
```suggestion
  describe '#index' do
```

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +  describe 'GET show book ' do
```suggestion
  describe '#show ' do
```

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +    it 'return http success if book exists' do
```suggestion
    it 'returns http success' do
```

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +    it { expect(response).to render_template :show }
Keep your codestyle
```suggestion
    it { expect(response).to render_template(:show) }
```

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +  describe 'book not found' do
Move this describe to `#show` tests

2021-05-04 12:46 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +    end
it { is_expected.to respond_with(:not_found) }

2021-05-04 12:46 UTC, legendado commented on spec/factories/book.rb
> +BOOK_MATERIAL = ['hardcover', 'glossy paper', 'matte paper'].freeze
Remove it

2021-05-04 12:46 UTC, legendado commented on spec/factories/book.rb
> +    material { BOOK_MATERIAL.sample }
Use FFaker

2021-05-04 12:46 UTC, legendado commented on spec/features/book_page_detail_spec.rb
> +RSpec.describe 'BookDetail' do
```suggestion
RSpec.describe 'Book page' do
```

2021-05-04 12:46 UTC, legendado commented on spec/models/author_spec.rb
> +require 'rails_helper'
Remove it

2021-05-04 12:46 UTC, legendado commented on spec/models/author_spec.rb
> +  let(:author) { FactoryBot.create(:author) }
```suggestion
  let(:author) { create(:author) }
```

2021-05-04 12:46 UTC, legendado commented on spec/models/author_spec.rb
> +  end
What is purpose of this test?
Remove it
Add validations tests and associations tests via `shoulda_matcher`

2021-05-04 12:46 UTC, legendado commented on spec/models/book_spec.rb
> +require 'rails_helper'
The same as above

2021-05-04 12:46 UTC, legendado commented on spec/models/category_spec.rb
> +require 'rails_helper'
Remove it

2021-05-04 12:46 UTC, legendado commented on spec/models/category_spec.rb
> +  let(:category) { FactoryBot.create(:category) }
```suggestion
  let(:category) { create(:category) }
```

2021-05-04 12:46 UTC, legendado commented on spec/models/category_spec.rb
> +  end
Remove it

2021-05-04 12:46 UTC, legendado commented on spec/support/config/simplecov.rb
> +  add_filter 'app/helpers'
Remove it

2021-05-14 11:51 UTC, legendado requested changes

2021-05-14 11:51 UTC, legendado commented on .rubocop.yml
> +
Trailing whitespace

2021-05-14 11:51 UTC, legendado commented on app/controllers/application_controller.rb
> +  include Rectify::ControllerHelpers
I think we can include this module only in places where we need it

2021-05-14 11:51 UTC, legendado commented on app/controllers/books_controller.rb
> +    end
I think we can remove it
Rails automatically will search the needed view base on the format

2021-05-14 11:51 UTC, legendado commented on app/decorators/book_decorator.rb
> +    "#{author.first_name} #{author.last_name}"
I think this part of code related to the `Author` decorator
Propose to move it to `AuthorDecorator` and use `decorates_association :author` method here

```ruby
class AuthorDecorator
  def full_name
    "#{first_name} #{last_name}"
  end
end

class BookDecorator
  decorates_association :author

  delegate :full_name, to: :author, prefix: true
end

book.author_full_name
```

2021-05-14 11:51 UTC, legendado commented on app/models/category.rb
> +class Category < ApplicationRecord
What about this comment?

2021-05-14 11:51 UTC, legendado commented on app/queries/books/filter_query.rb
> +      @category_id ? Book.where(category_id: @category_id) : Book.all
```suggestion
      Book.where(category_id: @category_id).or(Book.all)
```

2021-05-14 11:51 UTC, legendado commented on app/queries/books/filter_query.rb
> +      @sort_by_param = params[:sort_by]
```suggestion
      @sort_by = params[:sort_by]
```

2021-05-14 11:51 UTC, legendado commented on app/queries/books/filter_query.rb
> +      validate_sort_by_params? ? @sort_by_param : DEFAULT_SORT
```suggestion
      BOOK_FILTERING_ORDER[@sort_by] || DEFAULT_SORT
```

2021-05-14 11:51 UTC, legendado commented on app/queries/books/filter_query.rb
> +    end
It could be removed

2021-05-14 11:51 UTC, legendado commented on app/queries/books/filter_query.rb
> +    def sorting_params
Make it as private method

2021-05-14 11:51 UTC, legendado commented on app/queries/books/filter_query.rb
> +    def category_books_line
Make it as private method

2021-05-14 11:51 UTC, legendado commented on app/views/books/index.js.erb
> +$("#show-books").append('<%= escape_javascript render partial: "books/partials/book", collection: books, as: :book %>');
```suggestion
$("#show-books").append('<%= j render partial: "books/partials/book", collection: books, as: :book %>');
```

2021-05-14 11:51 UTC, legendado commented on app/views/books/partials/_categories_line.html.haml
> +      = render partial: 'books/partials/categories_line_item'
```suggestion
      = render 'books/partials/categories_line_item'
```

2021-05-14 11:51 UTC, legendado commented on app/views/books/partials/_categories_line.html.haml
> +
Trailing whitespace

2021-05-14 11:51 UTC, legendado commented on app/views/books/partials/_filter.haml
> +    = render partial: 'books/partials/categories_line'
```suggestion
    = render 'books/partials/categories_line'
```

2021-05-14 11:51 UTC, legendado commented on app/views/books/partials/_filter.haml
> +
Trailing whitespace

2021-05-14 11:51 UTC, legendado commented on config/initializers/constants.rb
> +    }.freeze
Remove it
It is a part of query object

2021-05-14 11:51 UTC, legendado commented on config/initializers/constants.rb
> +module Constants
Use 2 tabs instead of 4

2021-05-14 11:51 UTC, legendado commented on config/initializers/constants.rb
> +    SORT_ITEM_DEFAULT = SORT_LIST.detect { |sort| sort[:type] == :title_asc }
It is a bad practise to set value of constant dynamically

2021-05-14 11:51 UTC, legendado commented on config/initializers/constants.rb
> +    ].freeze
Can you simplify it?

2021-05-14 11:51 UTC, legendado commented on config/initializers/pagy.rb
> +require 'pagy/extras/metadata'
Why do you need it?

2021-05-14 11:51 UTC, legendado commented on config/initializers/pagy.rb
> +Pagy::VARS[:metadata] = [:scaffold_url, :count, :page, :prev, :next, :last]    # example
Why do you need it?

2021-05-14 11:51 UTC, legendado commented on config/initializers/pagy.rb
> +require 'pagy/extras/bootstrap'
Why do you need it?

2021-05-14 11:51 UTC, legendado commented on config/locales/books.yml
> +        title_desc: 'Title: Z - A'
Use 2 tabs instead of 4

2021-05-14 11:51 UTC, legendado commented on db/seeds.rb
> +    description:  FFaker::Book.description(10),
```suggestion
    description: FFaker::Book.description(10),
```

2021-05-14 11:51 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +    let!(:books) { create_list(:book, 3) }
Minimize the count of objects
```suggestion
    let!(:books) { create_list(:book, 2) }
```

2021-05-14 11:51 UTC, legendado commented on spec/controllers/books_controller_spec.rb
> +      expect(assigns(:books)).to eq(books.sort_by(&:title))
Use `match_array` instead of `eq`
```suggestion
      expect(assigns(:books)).to eq(books)
```

2021-05-14 11:51 UTC, legendado commented on spec/features/book_page_detail_spec.rb
> +    }
If you block has more than 1 line, prefer to use do-end syntax
```suggestion
    it do
      expect(book_page_detail).to have_btn_back
      expect(book_page_detail).to have_book_name(text: book.title)
      expect(book_page_detail).to have_book_authors(text: book.author.first_name)
    end

    it do
      book_page_detail.btn_read_more.click
      expect(book_page_detail).to have_book_all_description
    end
```

2021-05-14 11:51 UTC, legendado commented on spec/features/book_page_spec.rb
> +    it {
do-end

2021-05-14 11:51 UTC, legendado commented on spec/features/book_page_spec.rb
> +      create_list(:book, Constants::BOOKS_ON_PAGE)
Stub the constant to minimize count of objects

2021-05-14 11:51 UTC, legendado commented on spec/features/book_page_spec.rb
> +    it '12 books per page ' do
```suggestion
    it '12 books per page' do
```

2021-05-14 11:51 UTC, legendado commented on spec/features/book_page_spec.rb
> +      expect(book_page.book_content.size).to eq Constants::BOOKS_ON_PAGE
Follow your codestyle
```suggestion
      expect(book_page.book_content.size).to eq(Constants::BOOKS_ON_PAGE)
```

2021-05-14 11:51 UTC, legendado commented on spec/models/author_spec.rb
> +  describe 'with associations' do
```suggestion
  describe 'associations' do
```

2021-05-14 11:51 UTC, legendado commented on spec/models/author_spec.rb
> +  let(:author) { create(:author) }
We can remove it

2021-05-14 11:51 UTC, legendado commented on spec/models/author_spec.rb
> +  describe '#validate author' do
```suggestion
  describe 'validations' do
```

2021-05-14 11:51 UTC, legendado commented on spec/models/author_spec.rb
> +    end
```suggestion
   it { is_expected.to validate_presence_of(:first_name) }
```

2021-05-14 11:51 UTC, legendado commented on spec/models/book_spec.rb
> +  let(:category) { FactoryBot.create(:category) }
Remove all lets
You don't need it

2021-05-14 11:51 UTC, legendado commented on spec/models/book_spec.rb
> +  describe 'with associations' do
```suggestion
  describe 'associations' do
```

2021-05-14 11:51 UTC, legendado commented on spec/models/book_spec.rb
> +  describe '#validate book' do
```suggestion
  describe 'validations' do
```

2021-05-14 11:51 UTC, legendado commented on spec/models/book_spec.rb
> +    end
```suggestion
    it { is_expected.to validate_presence_of(:title) }
```

2021-05-14 11:51 UTC, legendado commented on spec/models/category_spec.rb
> +  let(:category) { create(:category) }
Remove it

2021-05-14 11:51 UTC, legendado commented on spec/models/category_spec.rb
> +  describe 'with associations' do
```suggestion
  describe 'associations' do
```

2021-05-14 11:51 UTC, legendado commented on spec/models/category_spec.rb
> +  end
```suggestion
  describe 'validations' do
    it { is_expected.to validate_presence_of(:title) } 
  end
```

2021-05-14 11:51 UTC, legendado commented on spec/rails_helper.rb
> +  config.include ApplicationHelper
Why do you need it?

2021-05-14 11:51 UTC, legendado commented on spec/support/config/simplecov.rb
> +  add_filter 'app/helpers'
What about this comment?

2021-05-14 11:51 UTC, legendado commented on spec/support/pages/home.rb
>    element :btn_shop, 'header', text: I18n.t('partials.header.shop')
Use normal names

2021-05-14 11:51 UTC, legendado commented on spec/support/pages/home.rb
> +  element :btn_start, 'a', text: I18n.t('pages.index.buttons.start')
Use normal name of element

2021-05-14 11:51 UTC, legendado commented on spec/support/pages/menu.rb
> +  element :btn_start, 'a', text: I18n.t('pages.index.buttons.start')
Use normal name of elements

2021-05-18 14:41 UTC, legendado requested changes

2021-05-18 14:41 UTC, legendado commented on app/decorators/author_decorator.rb
> +  def full_name
```suggestion
  delegate_all

  def full_name
```

2021-05-18 14:41 UTC, legendado commented on app/decorators/book_decorator.rb
> +  decorates_association :author
```suggestion
  BOOK_DESCRIPTION = 240

  decorates_association :author
```

2021-05-18 14:41 UTC, legendado commented on app/views/books/index.js.erb
> +$('#more-books').html("<%= j(render 'books/partials/next_page_link') if pagy_next_url(@pagy)%>");
```suggestion
$('#more-books').html("<%= j(render 'books/partials/next_page_link') if pagy_next_url(@pagy) %>");
```

2021-05-18 14:41 UTC, legendado commented on app/views/books/partials/_categories_line.html.haml
> +        = @books_count
Don't use instance variables in partials

2021-05-18 14:41 UTC, legendado commented on app/views/books/partials/_filter.haml
> +          = @presenter.search_books(params[:sort_by])
Don't use instance variables in partials

2021-05-18 14:41 UTC, legendado commented on config/initializers/constants.rb
> +module Constants
Use 2 tabs instead of 4

2021-05-18 14:41 UTC, legendado commented on spec/features/book_page_spec.rb
> +  let(:count_books) { stub_const 'Constants::BOOKS_ON_PAGE', 12 }
Use value less than 12
You don't need to create 12 books to testing pagination
`2` will be enough

2021-05-18 14:41 UTC, legendado commented on spec/models/author_spec.rb
> +  describe '#validations' do
```suggestion
  describe 'validations' do
```

2021-05-18 14:41 UTC, legendado commented on spec/models/author_spec.rb
> +    it { is_expected.to allow_value(FFaker::String.from_regexp(Constants::NAME_FORMAT)).for(:first_name) }
Move `FFaker::String.from_regexp(Constants::NAME_FORMAT)` to let helper

```ruby
let(:valid_text_value) { FFaker::String.from_regexp(Constants::NAME_FORMAT) }
```

2021-05-18 14:41 UTC, legendado commented on spec/models/book_spec.rb
> +  describe '#validations' do
```suggestion
  describe 'validations' do
```

2021-05-18 14:41 UTC, legendado commented on spec/models/book_spec.rb
> +  describe '#validations' do
Also, format and length validation for title is absent
Please, add it too

2021-05-18 14:41 UTC, legendado commented on spec/models/category_spec.rb
> +  describe '#validations' do
```suggestion
  describe 'validations' do
```

2021-05-18 14:41 UTC, legendado commented on spec/rails_helper.rb
> +require 'simplecov'
Move this require to the top of `rails_helper.rb`

2021-05-18 14:41 UTC, legendado commented on spec/rails_helper.rb
> +end
Move this code to `.simplecov` file at the root directory of project
You can check it [here](https://github.com/simplecov-ruby/simplecov#using-simplecov-for-centralized-config)

2021-05-18 14:41 UTC, legendado commented on spec/support/pages/menu.rb
> +  element :btn_start, 'a', text: I18n.t('pages.index.buttons.start')
Use normal name of elements

2021-05-19 07:44 UTC, legendado requested changes
Looks good 👍 
Just a few comments

2021-05-19 07:44 UTC, legendado commented on app/views/books/index.html.haml
> +        = render partial: 'books/partials/next_page_link'
```suggestion
        = render 'books/partials/next_page_link', pagy: @pagy
```

2021-05-19 07:44 UTC, legendado commented on app/views/books/index.js.erb
> +$('#more-books').html('<%= j(render 'books/partials/next_page_link') if pagy_next_url(@pagy) %>');
```suggestion
$('#more-books').html('<%= j(render 'books/partials/next_page_link') if pagy_next_url(pagy) %>');
```

2021-05-19 07:44 UTC, legendado commented on spec/features/book_page_spec.rb
> +    it '12 books per page' do
```suggestion
    it "renders #{count_books} books per page" do
```

2021-05-19 10:28 UTC, legendado requested changes

2021-05-19 10:28 UTC, legendado commented on app/views/books/index.js.erb
> +$('#more-books').html('<%= j(render 'books/partials/next_page_link') %>');
Why did you remove condition `if pagy_next_url(pagy)`?

2021-05-19 10:28 UTC, legendado commented on app/views/books/partials/_next_page_link.haml
> += link_to t('.button'), pagy_next_url(@pagy), class: 'btn btn-primary', remote: true, id: 'next_link'
Don't use instance variable in partials
```suggestion
= link_to t('.button'), pagy_next_url(pagy), class: 'btn btn-primary', remote: true, id: 'next_link'
```

2021-05-19 10:28 UTC, legendado commented on app/views/books/index.html.haml
> +      = render 'books/partials/next_page_link', pagy: @pagy
Do we need `if pagy_next_url(@pagy)` condition here?

2021-05-19 11:43 UTC, legendado approved these changes

2021-05-19 11:45 UTC, merged