Feature/step 3
skoomer/bookstore pull request #3
Opened 2021-05-19 12:26 UTC by skoomer

•	Log in page
	•	Sign up page
	•	Forgot password page
	•	Dynamic headers/footers for all pages for guest/user
	•	Log in logic with dynamic error setting(Simple Form)
	•	Sign up logic with dynamic error setting(Simple Form)
	•	Registration via Omniauth-Facebook
	•	Send notification to user about registration/forgot password 
	•	Write tests (unit, feature) for your new code.

2021-05-24 11:26 UTC, AnastasiaBortnovska approved these changes

2021-05-24 11:26 UTC, AnastasiaBortnovska commented on app/models/user.rb
> +      # user.provider = auth.provider
do you need it?

2021-05-24 11:26 UTC, AnastasiaBortnovska commented on app/webpack/js/facebook.js
> +
do you need it?

2021-05-24 11:26 UTC, AnastasiaBortnovska commented on config/initializers/devise.rb
> +  config.password_length = 6..128
```suggestion
  config.password_length = 8..128
```

2021-05-24 11:26 UTC, AnastasiaBortnovska commented on db/migrate/20210427152300_add_omniauth_to_users.rb
> +class AddOmniauthToUsers < ActiveRecord::Migration[6.1]
move it to previous migration

2021-05-24 11:26 UTC, AnastasiaBortnovska commented on spec/features/users/sign_up_spec.rb
> +      sign_up.sign_up_button.click
you could use site_prism for it

2021-05-24 11:26 UTC, AnastasiaBortnovska commented on spec/support/config/database_cleaner.rb
> +# frozen_string_literal: true
why do you need it?

2021-05-25 12:25 UTC, OlexandrToloshnyak approved these changes
👍

2021-05-25 12:25 UTC, OlexandrToloshnyak commented on Gemfile
> +  gem 'database_cleaner'
add gem version

2021-05-25 12:25 UTC, OlexandrToloshnyak commented on app/mailers/application_mailer.rb
> +  # default from: 'from@example.com'
are you need it?

2021-05-25 12:25 UTC, OlexandrToloshnyak commented on app/mailers/application_mailer.rb
> +  # end
this too

2021-05-25 13:50 UTC, legendado requested changes

2021-05-25 13:50 UTC, legendado commented on Gemfile
> +  gem 'database_cleaner'
Remove this gem
Use `transactional_fixtures` instead

2021-05-25 13:50 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    skip_before_action :verify_authenticity_token, only: :facebook
Why do you need to skip `authenticity_token`?

2021-05-25 13:50 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +        set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
i18n

2021-05-25 13:50 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +        session['devise.facebook_data'] = request.env['omniauth.auth']
Add flash message to failure case

2021-05-25 13:50 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    def authentication_and_redirect(path_default: '')
Where do you use this method?

2021-05-25 13:50 UTC, legendado commented on app/mailers/application_mailer.rb
> +  # default from: 'from@example.com'
Uncomment this line

2021-05-25 13:50 UTC, legendado commented on app/mailers/application_mailer.rb
> +  default from: 'any_from_address@example.com'
It could be removed

2021-05-25 13:50 UTC, legendado commented on app/models/user.rb
> +  def self.from_omniauth(auth)
```suggestion
            on: :create

  def self.from_omniauth(auth)
```

2021-05-25 13:50 UTC, legendado commented on app/models/user.rb
> +    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
Use `find_or_create_by`

2021-05-25 13:50 UTC, legendado commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
Why do you need this view?

2021-05-25 13:50 UTC, legendado commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>
i18n

2021-05-25 13:50 UTC, legendado commented on app/views/devise/mailer/email_changed.html.erb
> +<% end %>
i18n

2021-05-25 13:50 UTC, legendado commented on app/views/devise/mailer/password_change.html.erb
> +<p>We're contacting you to notify you that your password has been changed.</p>
i18n

2021-05-25 13:50 UTC, legendado commented on app/views/devise/mailer/reset_password_instructions.html.erb
> +<p>Your password won't change until you access the link above and create a new one.</p>
i18n

2021-05-25 13:50 UTC, legendado commented on app/views/devise/mailer/unlock_instructions.html.erb
> +<p><%= link_to 'Unlock my account', unlock_url(@resource, unlock_token: @token) %></p>
I18n

2021-05-25 13:50 UTC, legendado commented on app/models/user.rb
> +          :confirmable,
Are you sure that we need that the User should be a `confirmable`?

2021-05-25 13:50 UTC, legendado commented on app/models/user.rb
> +  # end
Remove it

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +  = simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put, class: 'general-form' }) do |f|
Use `wrapper` configuration in `simple_form`

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +      = f.input :password, label_html: { class: 'control-label input-label' }, label: t('forgot_password.password_label'), placeholder: t('forgot_password.password_placeholder')
You can move label class to simple_form wrapper

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +      = f.input :password_confirmation, label_html: { class: 'control-label input-label' }, label: t('forgot_password.confirm_password_label'), placeholder: t('forgot_password.confirm_password_label'
You can move label class to simple_form wrapper

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +  = form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post, class: "general-form" }) do |f|
Use `simple_form` and wrappers

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      = f.submit t('forgot_password.email_instructions'), class: "btn btn-default mb-20"
Move html classes to wrapper

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +        = alert
Why do you need it?

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      %a.in-gold-500.mb-20{href: "/users/sign_in" }= t('forgot_password.cancel')
Use link_to helper

2021-05-25 13:50 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +  = simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html:{ class: 'general-form' }) do |f|
Use wrapper

2021-05-25 13:50 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +      = f.submit t('signup.sign_up'), class: 'btn btn-default mb-20', id: 'sign_up', method: :post
Wrapper

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      = t('auth_user.forgot_password')
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      = t('forgot_password.instructions_message')
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      = f.email_field :email, autofocus: true, placeholder: t('forgot_password.enter_email'), autocomplete: "email", class: "form-control"
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      = f.submit t('forgot_password.email_instructions'), class: "btn btn-default mb-20"
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      %a.in-gold-500.mb-20{href: "/users/sign_in" }= t('forgot_password.cancel')
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +      = t('signup.sign_up')
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +      = t('or')
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +      = t('signup.have_account')
Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +      = link_to 'Log in', new_user_session_path
I18n

2021-05-25 13:50 UTC, legendado commented on app/views/devise/sessions/new.html.haml
> +%main.container.general-main-wrap
The same as above:
1. Wrapper
2. Lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/devise/shared/_error_messages.html.erb
> +<% if resource.errors.any? %>
Do we need this partial?

2021-05-25 13:50 UTC, legendado commented on app/views/devise/shared/_links.html.erb
> +<%- if controller_name != 'sessions' %>
Do we need this partial?

2021-05-25 13:50 UTC, legendado commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
Do we need this view?

2021-05-25 13:50 UTC, legendado commented on app/views/partials/_footer.haml
> +                        %a.nav-link{href: "#"}= link_to t('.home'), root_path
```suggestion
                        = link_to t('.home'), root_path, class: 'nav-link'
```

2021-05-25 13:50 UTC, legendado commented on app/views/partials/_footer.haml
> +                        %a.nav-link{href: "#"}= link_to t('.shop'), books_path
```suggestion
                        = link_to t('.shop'), books_path, class: 'nav-link'
```

2021-05-25 13:50 UTC, legendado commented on app/views/partials/_header.haml
> +                    = link_to 'settings', user_session_path
i18n

2021-05-25 13:50 UTC, legendado commented on app/views/partials/_header.haml
> +                    = link_to  'menu order'
i18n

2021-05-25 13:50 UTC, legendado commented on app/views/partials/_header.haml
> +                    = link_to 'log out', destroy_user_session_path, method: :delete
i18n

2021-05-25 13:50 UTC, legendado commented on app/views/partials/_header.haml
> +                  = t('partials.header.my_account')
lazylookup

2021-05-25 13:50 UTC, legendado commented on app/views/partials/_header.haml
> +                    = link_to t('signup.sign_up'), new_user_registration_path, class: 'collapse-link'
lazylookup

2021-05-25 13:50 UTC, legendado commented on config/credentials.yml.enc
> +oYqmhHsx9WDnwJjfjHKUsDtn5Tlamb3qCME4jcAi2wQgOQu+DqMF0t/Mpi5HY5E6akp6RdlbTTI05D/5RyxN55NFO7zhOvQUELpBAy7Q6Sky1o0hfzLOpds2yczRpVvTX7nG2FXHJUzdbPibv75uMqlLH3XH1SKqK3avsazi/xXj14Q4VXtEiJScy2OJcfkdU9aesrG
Remove this file
Also, don't forget to remove `config/master.key`

2021-05-25 13:50 UTC, legendado commented on config/environments/production.rb
> +  # config.config.read_encrypted_secrets = true
Remove it

2021-05-25 13:50 UTC, legendado commented on config/environments/development.rb
> +  config.action_mailer.perform_deliveries = true
Remove it

2021-05-25 13:50 UTC, legendado commented on config/environments/development.rb
> +  }
Use `letter_opener` gem in development environment

2021-05-25 13:50 UTC, legendado commented on config/initializers/devise.rb
> +  require "omniauth-facebook"
Why do you need it?

2021-05-25 13:50 UTC, legendado commented on config/initializers/devise.rb
> +  config.omniauth :facebook, Rails.application.credentials.dig(:facebook, :APP_ID), Rails.application.credentials.dig(:facebook, :APP_SECRET)
Do not upcase values in credentials

2021-05-25 13:50 UTC, legendado commented on config/initializers/simple_form_bootstrap.rb
> +# frozen_string_literal: true
Why do you need this file?

2021-05-25 13:50 UTC, legendado commented on config/locales/authenticate.yml
> +
Trailing whitespace

2021-05-25 13:50 UTC, legendado commented on db/migrate/20210427143404_devise_create_users.rb
> +      t.string   :last_sign_in_ip
Why do you need it?

2021-05-25 13:50 UTC, legendado commented on db/migrate/20210427143404_devise_create_users.rb
> +      t.string   :unconfirmed_email # Only if using reconfirmable
Why do you need it?

2021-05-25 13:50 UTC, legendado commented on db/migrate/20210427143404_devise_create_users.rb
> +      # t.datetime :locked_at
Clean up

2021-05-25 13:50 UTC, legendado commented on lib/templates/haml/scaffold/_form.html.haml
> +-# frozen_string_literal: true
Remove this file

2021-05-25 13:50 UTC, legendado commented on app/models/user.rb
> +          :trackable,
Are you sure that we need that the User should be a `trackable`?

2021-05-25 13:50 UTC, legendado commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +        request.env['devise.mapping'] = Devise.mappings[:user]
Why do you need this line?
You have the same logic in `stub_env_for_omniauth_fb` method

2021-05-25 13:50 UTC, legendado commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +        stub_env_for_omniauth_fb
Move to before action

2021-05-25 13:50 UTC, legendado commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +    let(:get_facebook) { get :facebook }
Remove it

2021-05-25 13:50 UTC, legendado commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +  RSpec.describe OmniauthCallbacksController do
Group this tests to common context:
```ruby
describe '#facebook' do
  ...
end
```

2021-05-25 13:50 UTC, legendado commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +        get_facebook
Move to before action

2021-05-25 13:50 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +    expect(forgot_password).to have_email_instriction
Can we use `be_all_there` helper?

2021-05-25 13:50 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +    it 'Empty email and password' do
Rename this test according to logic of him
You test that alert message is display, so:
```suggestion
    it 'displays alert message' do
```

2021-05-25 13:50 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +      expect(forgot_password.alert_message.visible?).to eq(true)
Use `be_visible`

2021-05-25 13:50 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +    expect(sign_in).to have_sign_up_link
`be_all_there`

2021-05-25 13:50 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +      sign_in.visit_and_login_as(user.email, user.password)
What is purpose of this test?

2021-05-25 13:50 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +    expect(sign_up).to have_sign_up_button
`be_all_there`

2021-05-25 13:50 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +    it 'Empty email and password' do
Fix the name of test

2021-05-25 13:50 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +      sign_up.visit_and_sign_up_as(user.email, user.password)
What is purpose of this test?

2021-05-25 13:50 UTC, legendado commented on spec/models/user_spec.rb
> +require 'rails_helper'
Remove it

2021-05-25 13:50 UTC, legendado commented on spec/models/user_spec.rb
> +RSpec.describe User do
`from_omniauth` method tests is absent

2021-05-25 13:50 UTC, legendado commented on spec/support/config/stub_facebook.rb
> +      }
Can we make it more dynamically?

2021-05-25 21:09 UTC, skoomer commented on config/environments/development.rb
> +  }
> Use `letter_opener` gem in development environment

cool gem thanks

2021-05-25 21:17 UTC, skoomer commented on config/initializers/simple_form_bootstrap.rb
> +# frozen_string_literal: true
> Why do you need this file?

for simple form
Simple Form can be easily integrated to the Bootstrap. To do that you have to use the bootstrap option in the install generator.

2021-05-27 10:28 UTC, legendado requested changes

2021-05-27 10:28 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +          set_flash_message(:notice, :success,
Move it to separate method:
```ruby
success_flash_message if is_navigational_format?

def success_flash_message
 set_flash_message ...
end
```

2021-05-27 10:28 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +
What is empty lines around?

2021-05-27 10:28 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +
```suggestion
        session['devise.facebook_data'] = request.env['omniauth.auth']
        failure_flash_message if is_navigational_format?
        redirect_to new_user_registration_url
```

2021-05-27 10:28 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +    end
It could be removed

2021-05-27 10:28 UTC, legendado commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
Clean up this comments

2021-05-27 10:28 UTC, legendado commented on app/models/user.rb
> +            on: :create
What about `update` action?
Remove it
```suggestion
```

2021-05-27 10:28 UTC, legendado commented on app/models/user.rb
> +    User.find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
```suggestion
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
```

2021-05-27 10:28 UTC, legendado commented on app/models/user.rb
> +      user.password = Devise.friendly_token[0, 20]
What about provider, uid and avatar?

2021-05-27 10:28 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +  = simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put, class: 'general-form' }) do |f|
https://github.com/heartcombo/simple_form#the-wrappers-api

2021-05-27 10:28 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +  = simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post, class: "general-form" }) do |f|
https://github.com/heartcombo/simple_form#the-wrappers-api

2021-05-27 10:28 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +  = simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html:{ class: 'general-form' }) do |f|
https://github.com/heartcombo/simple_form#the-wrappers-api

2021-05-27 10:28 UTC, legendado commented on app/views/devise/sessions/new.html.haml
> +  = simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'general-form' }, validate: true) do |f|
https://github.com/heartcombo/simple_form#the-wrappers-api

2021-05-27 10:28 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +      = f.input :password, wrapper_html: { class: 'password' }, label: t('.password_label'), placeholder: t('.password_placeholder')
What is the strange class?

2021-05-27 10:28 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +      = f.input :password_confirmation, wrapper_html: { class: 'password_confirmation' }, label: t('.confirm_password_label'), placeholder: t('.confirm_password_label')
What is the strange class?

2021-05-27 10:28 UTC, legendado commented on app/views/devise/sessions/new.html.haml
> +      = f.input :email, wrapper_html: { class: 'email' }, label: t('auth_user.email_label'), placeholder: t('.email_placeholder')
What is the strange class?

2021-05-27 10:28 UTC, legendado commented on app/views/devise/sessions/new.html.haml
> +      = f.input :password, wrapper_html: { class: 'password' }, label: t('.password_label'), placeholder: t('.password_placeholder')
What is the strange class?

2021-05-27 10:28 UTC, legendado commented on app/views/devise/sessions/new.html.haml
> +        = f.input_field :remember_me, as: :boolean, wrapper_html: { class: 'checkbox-input' }, hidden: 'true', id: 'remember_me'
What is the strange class?

2021-05-27 10:28 UTC, legendado commented on app/views/devise/sessions/new.html.haml
> +        = alert
Why do you need it?

2021-05-27 10:28 UTC, legendado commented on app/views/partials/_header.haml
> +                  = t('.my_account')
I think, you don't need to display `My Account` tab if user is not logged in
Show just `Log In` and `Sign In` buttons

2021-05-27 10:28 UTC, legendado commented on config/environments/development.rb
> +
Remove trailing whitespace

2021-05-27 10:28 UTC, legendado commented on config/environments/production.rb
> +  :enable_starttls_auto => true
Use symbol hash syntax
Add tabs

2021-05-27 10:28 UTC, legendado commented on config/initializers/devise.rb
> +  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
You can change it

2021-05-27 10:28 UTC, legendado commented on config/initializers/simple_form.rb
> +  # config.label_text = lambda { |label, required, explicit_label| "#{required} #{label}" }
You can configure it

2021-05-27 10:28 UTC, legendado commented on config/initializers/simple_form.rb
> +  # config.label_class = nil
You can configure it

2021-05-27 10:28 UTC, legendado commented on config/initializers/simple_form.rb
> +  # config.required_by_default = true
You can configure it

2021-05-27 10:28 UTC, legendado commented on config/initializers/simple_form.rb
> +  # config.input_class = nil
You can configure it

2021-05-27 10:28 UTC, legendado commented on config/locales/devise.en.yml
> +
This comment could be removed

2021-05-27 10:28 UTC, legendado commented on config/locales/partials.yml
> +      menu_order: order
```suggestion
      menu_order: Order
```

2021-05-27 10:28 UTC, legendado commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +          allow(User).to receive(:from_omniauth).and_return(build(:user))
You don't need to stub :from_omniauth method
Configure `stub_env_for_omniauth_fb` method

2021-05-27 10:28 UTC, legendado commented on spec/controllers/users/omniauth_callbacks_controller_spec.rb
> +          allow(User).to receive(:from_omniauth).and_return(create(:user))
You don't need to stub :from_omniauth method
Configure stub_env_for_omniauth_fb method

2021-05-27 10:28 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +  describe 'Forgot password' do
You don't need this describe
Remove it

2021-05-27 10:28 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +      expect(page).to have_current_path('/users/sign_in')
Use route helper

2021-05-27 10:28 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +    it 'invalid values' do
Change name of test according to logic of test

2021-05-27 10:28 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +    it 'redirect to root_path if valid login' do
```suggestion
    it 'redirects to root_path if valid login' do
```

2021-05-27 10:28 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +    it 'sign up with valid values' do
```suggestion
    it 'signs up with valid values' do
```

2021-05-27 10:28 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +  describe 'Click to Sign up button' do
Also, add failure cases

2021-05-27 10:28 UTC, legendado commented on spec/models/user_spec.rb
> +  describe '#self.from_omniauth' do
```suggestion
  describe '.from_omniauth' do
```

2021-05-27 10:28 UTC, legendado commented on spec/models/user_spec.rb
> +  describe '#self.from_omniauth' do
https://www.betterspecs.org/

2021-05-27 10:28 UTC, legendado commented on spec/models/user_spec.rb
> +    it 'returns or cteate user' do
Make a 2 different context: when user present and when user is not exist

2021-05-27 10:28 UTC, legendado commented on spec/support/config/devise.rb
> +OmniAuth.config.add_mock(:facebook, OmniAuth.config.mock_auth[:facebook])
1. Remove it from here
2. Create a file `omniauth.rb` in support page
3. Follow the next logic:
```ruby
module OmniAuthTestHelper
  def stub_facebook_omniauth(uid: '', picture: '', email: '')
    OmniAuth.config.test_mode = true
    OmniAuth.config.mock_auth[:facebook] = OmniAuth::AuthHash.new(provider: :facebook, uid: uid,
                                                                  info: { picture_url: picture, email: email })
  end
end

RSpec.configure do |config|
  config.include(OmniAuthTestHelper, type: :controller)
  config.include(OmniAuthTestHelper, type: :model)
  config.include(OmniAuthTestHelper, type: :feature)
end
```
And usage:
```ruby
let(:user) { create(:user) }

before do
   stub_facebook_omniauth(email: user.email)
end

...
```

2021-05-27 16:16 UTC, skoomer commented on spec/support/config/devise.rb
> +OmniAuth.config.add_mock(:facebook, OmniAuth.config.mock_auth[:facebook])
> 1. Remove it from here
> 2. Create a file `omniauth.rb` in support page
> 3. Follow the next logic:
> 
> ```ruby
> module OmniAuthTestHelper
>   def stub_facebook_omniauth(uid: '', picture: '', email: '')
>     OmniAuth.config.test_mode = true
>     OmniAuth.config.mock_auth[:facebook] = OmniAuth::AuthHash.new(provider: :facebook, uid: uid,
>                                                                   info: { picture_url: picture, email: email })
>   end
> end
> 
> RSpec.configure do |config|
>   config.include(OmniAuthTestHelper, type: :controller)
>   config.include(OmniAuthTestHelper, type: :model)
>   config.include(OmniAuthTestHelper, type: :feature)
> end
> ```
> 
> And usage:
> 
> ```ruby
> let(:user) { create(:user) }
> 
> before do
>    stub_facebook_omniauth(email: user.email)
> end
> 
> ...
> ```

I tried to do so, such a way does not cover tests.

2021-06-01 15:56 UTC, legendado requested changes

2021-06-01 15:56 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +      redirect_to new_user_registration_url
Are you sure that you contain in this method just flash message?

2021-06-01 15:56 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +      @user = User.from_omniauth(request.env['omniauth.auth'])
Use local variable instead of instance

2021-06-01 15:56 UTC, legendado commented on app/models/user.rb
> +            on: :update
Do we need validate password just on `update` action?
Remove it

2021-06-01 15:56 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +    = f.input :password, label: false, placeholder: t('.password_placeholder')
You can configure labels into `simple_form` intializer

2021-06-01 15:56 UTC, legendado commented on app/views/devise/passwords/edit.html.haml
> +  = simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put, class: 'general-form' }, defaults: { wrapper_html: { class: 'form_group mb-30' } }) do |f|
You can use wrappers into `simple_form` initializer to remove `class: 'general-form`, `form_group mb-30`, etc
More about wrappers you can find [here](https://github.com/heartcombo/simple_form#the-wrappers-api)

2021-06-01 15:56 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +  = simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post, class: "general-form" }, defaults: { wrapper_html: { class: 'form_group mb-30' } }) do |f|
Wrapper API

2021-06-01 15:56 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +    = f.input :email, autofocus: true, placeholder: t('.email_placeholder'),label: false
You can configure labels within simple_form configuration

2021-06-01 15:56 UTC, legendado commented on app/views/devise/passwords/new.html.haml
> +      = f.submit t('.email_instructions'), class: "btn btn-default mb-20" , id: 'email_button'
Prefer to use single quotes

2021-06-01 15:56 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +  = simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: 'general-form' }, defaults: { wrapper_html: { class: 'form_group mb-30' } }) do |f|
Wrappers API

2021-06-01 15:56 UTC, legendado commented on app/views/devise/registrations/new.html.haml
> +    = f.input :password_confirmation, label: false, placeholder: t('.confirm_password_label')
Configure labels/placeholders within simple_form configuration

2021-06-01 15:56 UTC, legendado commented on app/views/devise/sessions/new.html.haml
> +  = simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'general-form' }, validate: true ) do |f|
The same as above

2021-06-01 15:56 UTC, legendado commented on app/views/partials/_header.haml
> +                    = link_to  t('.menu_order')
```suggestion
                    = link_to t('.menu_order')
```

2021-06-01 15:56 UTC, legendado commented on spec/factories/users.rb
> +    provider { :facebook }
Move it to trait

2021-06-01 15:56 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +  end
What is the purpose to this test?
1. Rename it
2. Do you have any alerts after submitting form? If you have it than propose to add test that check s this alert text

2021-06-01 15:56 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +    it 'invalid values' do
What `invalid values`? Rename this test according to logic of test

2021-06-01 15:56 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +      expect(page).not_to have_selector 'div.alert.alert-danger',
Move to page object

2021-06-01 15:56 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +      expect(page).not_to have_selector 'div.alert.alert-danger',
Also, add more tests for success scenario

2021-06-01 15:56 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +    it 'invalid values' do
Rename it

2021-06-01 15:56 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +      expect(page).not_to have_selector 'div.alert.alert-success',
1. Move to page object
2. Add test that checks that failure alerts are present

2021-06-01 15:56 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +      expect(page).to have_current_path(root_path, ignore_query: true)
Also, add tests for alert and `Sign In`/`Log In` button that should be hided after successfully signing in

2021-06-01 15:56 UTC, legendado commented on spec/models/user_spec.rb
> +      it 'when returns user' do
```suggestion
      it 'returns user' do
```

2021-06-01 15:56 UTC, legendado commented on spec/models/user_spec.rb
> +        expect { described_class.from_omniauth(auth) }.to change(described_class, :count).by(1)
Use `from(0).to(1)` instead of `by(1)`

2021-06-01 15:56 UTC, legendado commented on spec/support/config/devise.rb
> -RSpec.configure do |config|
Why did you drop it?

2021-06-01 15:56 UTC, legendado commented on spec/support/config/stub_facebook.rb
> +  end
Move it to `devise`  configuration

2021-06-01 15:56 UTC, legendado commented on spec/support/config/stub_facebook.rb
> +module StubFacebook
Why do you need this helper?
You already has the `omniauth` helper

2021-06-01 15:56 UTC, legendado commented on spec/support/pages/sign_in_page.rb
> +  element :log_in_button, 'input#log_in'
```suggestion
  element :email_input, '#user_email'
  element :password_input, '#user_password'
  element :log_in_button, '#log_in'
```

2021-06-01 15:56 UTC, legendado commented on spec/rails_helper.rb
> +  config.include OmniAuthTestHelper
You already included it in `spec/support/config/omniauth.rb`

2021-06-07 09:27 UTC, legendado requested changes

2021-06-07 09:27 UTC, legendado commented on app/controllers/users/omniauth_callbacks_controller.rb
> +      redirect_to new_user_registration_url
It is not a part of failure flash message
Move this redirect to `facebook` action

2021-06-07 09:27 UTC, legendado commented on config/locales/simple_form.en.yml
> +        password_confirmation: password
Nit: Propose to make more informative (e.g. `Enter email`, `Enter password`, etc)

2021-06-07 09:27 UTC, legendado commented on spec/factories/users.rb
> +    password { Devise.friendly_token[0, 20] }
Can we set `Devise.friendly_token[0, 20]` as default password and remove it from this trait?

2021-06-07 09:27 UTC, legendado commented on spec/factories/users.rb
> +  trait :with_facebook do
Always use trait inside `factory` block

2021-06-07 09:27 UTC, legendado commented on spec/factories/users.rb
> +  trait :with_facebook do
Also, propose to add `uid` too

2021-06-07 09:27 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +  end
Propose to split it to different contexts:
```ruby
before do
  forgot_password.fill_in_form(email)
end

context 'when valid email' do
  let(:user) { create(:user) }
  let(:email) { user.email } 

  it 'redirects to root path' do
    # ...
  end

  it 'sets success flash message' do
    # ...
  end
end

context 'when invalid email' do
  let(:email) { FFaker::Internet.email }

  it 'redirects to root path' do
  end

  it 'sets failure flash message' do
  end
end

2021-06-07 09:27 UTC, legendado commented on spec/features/users/forgot_password_spec.rb
> +    expect(home_page).not_to have_selector 'div.alert.alert-danger',
Move it to page object

2021-06-07 09:27 UTC, legendado commented on spec/features/users/sign_in_spec.rb
> +  describe 'validations' do
Use the same structure as above

2021-06-07 09:27 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +  describe 'validations' do
Use the same structure of tests as above

2021-06-07 09:27 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +      expect(home_page).not_to have_selector 'div.alert.alert-success',
Move to page object

2021-06-07 09:27 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +      expect(home_page).not_to have_link('a.log_in_link')
Use `site_prism` elements

2021-06-07 09:27 UTC, legendado commented on spec/models/user_spec.rb
> +  describe 'with validation' do
`with` word uses only within `context`
```suggestion
  describe 'validations' do
```

2021-06-07 09:27 UTC, legendado commented on spec/support/pages/home.rb
> +  element :div_danger, 'div.alert.alert-danger'
```suggestion
  element :success_flash_message, 'div.alert.alert-success'
  element :failure_flash_message, 'div.alert.alert-danger'
```

2021-06-08 10:48 UTC, legendado requested changes

2021-06-08 10:48 UTC, legendado commented on app/models/user.rb
> +  DEFAULT_PASSWORD = Devise.friendly_token[0, 20]
Do not set dynamic constants
Remove it

2021-06-08 10:48 UTC, legendado commented on spec/factories/users.rb
> +      password { User::DEFAULT_PASSWORD }
Why do you need it?
Remove it

2021-06-08 10:48 UTC, legendado commented on spec/features/users/sign_up_spec.rb
> +    it 'hide links sign_up and log_in after success' do
```suggestion
    it 'hides links sign_up and log_in after success' do
```

2021-06-08 10:48 UTC, legendado commented on spec/support/pages/forgot_password.rb
> +  element :forgot_title, 'h1'
If there is a few h1 tags?
```suggestion
  element :forgot_title, 'h1', text: I18n.t(:forgot_password_title)
```

2021-06-08 10:48 UTC, legendado commented on spec/support/pages/forgot_password.rb
> +  element :email_instriction, 'p'
The same as above: add text value for `p` tag

2021-06-08 10:48 UTC, legendado commented on spec/support/pages/forgot_password.rb
> +  element :email_button, 'input#email_button'
```suggestion
  element :email_button, '#email_button'
```

2021-06-08 10:48 UTC, legendado commented on spec/support/pages/forgot_password.rb
> +  element :cancel_link, 'a'
Add text

2021-06-08 10:48 UTC, legendado commented on spec/support/pages/forgot_password.rb
> +  element :email_input, 'input#user_email'
```suggestion
  element :email_input, '#user_email'
```

2021-06-08 10:48 UTC, legendado commented on spec/support/pages/sign_up_page.rb
> +  element :sign_up_button, 'input#sign_up'
```suggestion
  element :email_input, '#user_email'
  element :password_input, '#user_password'
  element :password_confirm_input, '#user_password_confirmation'
  element :sign_up_button, '#sign_up'
```

2021-06-09 08:10 UTC, legendado approved these changes

2021-06-09 08:10 UTC, merged