Feature/step 4
skoomer/bookstore pull request #4
Opened 2021-06-09 15:57 UTC by skoomer

- User Profile page
- Personal information form
- Delete account form
- Addresses form
- Tests
-  heroku
-  https://thawing-dusk-89266.herokuapp.com/

2021-06-10 13:59 UTC, AnastasiaBortnovska commented on app/views/devise/registrations/_edit_email.html.haml
> += simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html:{ method: :put }) do |f|
```suggestion
= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), method: :put ) do |f|
```

2021-06-10 13:59 UTC, AnastasiaBortnovska commented on app/views/devise/registrations/_edit_password.html.haml
> += simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html:{ method: :put }) do |f|
```suggestion
= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), method: :put ) do |f|
```

2021-06-10 13:59 UTC, AnastasiaBortnovska commented on config/locales/devise.en.yml
> +
remove

2021-06-10 13:59 UTC, AnastasiaBortnovska commented on db/seeds.rb
> +end
do you need it?

2021-06-10 13:59 UTC, AnastasiaBortnovska commented on spec/controllers/users/registrations_controller_spec.rb
> +  let(:address_empty) do
move to the describe where its need

2021-06-10 13:59 UTC, AnastasiaBortnovska commented on spec/controllers/users/registrations_controller_spec.rb
> +  let(:address) { build(:address) }
```suggestion
  let(:address) { attributes_for(:address) }
```

2021-06-11 19:42 UTC, AnastasiaBortnovska approved these changes

2021-06-11 19:42 UTC, AnastasiaBortnovska commented on spec/controllers/users/registrations_controller_spec.rb
> +  # let(:address) { attributes_for(:address) }
remove it

2021-06-17 11:01 UTC, legendado requested changes

2021-06-17 11:01 UTC, legendado commented on .gitignore
> +/config/credentials/development.key
Remove it

2021-06-17 11:01 UTC, legendado commented on .gitignore
> +/config/credentials/production.key
Remove it

2021-06-17 11:01 UTC, legendado commented on .gitignore
> -*.key
Why did you remove it?
Keep it

2021-06-17 11:01 UTC, legendado commented on app/controllers/users/registrations_controller.rb
> +    def edit; end
Why do you need it?

2021-06-17 11:01 UTC, legendado commented on app/models/user.rb
> +  has_one  :billing_address, dependent: :destroy
```suggestion
  has_one :shipping_address, dependent: :destroy
  has_one :billing_address, dependent: :destroy
```

2021-06-17 11:01 UTC, legendado commented on app/views/devise/registrations/_address_form.html.haml
> += simple_form_for resource, as: resource_name, url: registration_path(resource_name), method: :put do |f|
Use 2 tabs instead of 2

2021-06-17 11:01 UTC, legendado commented on app/views/devise/registrations/_edit_email.html.haml
> += simple_form_for(resource, as: resource_name, url: registration_path(resource_name), method: :patch ) do |f|
```suggestion
= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), method: :put ) do |f|
```

2021-06-17 11:01 UTC, legendado commented on app/views/devise/registrations/edit.html.haml
> +          = label_tag 'checkBox', t('.confirm')
Use snake case

2021-06-17 11:01 UTC, legendado commented on app/webpack/js/users.js
> +    $('#checkBox').click(function() {
Nice copy past

2021-06-17 11:01 UTC, legendado commented on config/credentials/development.key
> +2225c8113ce45f84589d3098031c86f1
What is that? Are you kidding me?

2021-06-17 11:01 UTC, legendado commented on config/credentials/production.key
> +e56959b623d49c45394f92ec797dd209
What is that? Are you kidding me?

2021-06-17 11:01 UTC, legendado commented on app/webpack/packs/users/settings/update.js
> +$(document).ready(function() {
Why do you need this function if it is not use anywhere?

2021-06-17 11:01 UTC, legendado commented on config/environments/test.rb
> +
Trailing whitespace

2021-06-17 11:01 UTC, legendado commented on db/migrate/20210427143404_devise_create_users.rb
> +
Trailing whitespace

2021-06-17 11:01 UTC, legendado commented on db/migrate/20210517155123_create_addresses.rb
> +      t.references :user
Database table does not match to the model

2021-06-17 11:01 UTC, legendado commented on db/seeds.rb
> +  )
```suggestion
  User.create(email: 'exampl@gmail.com', password: 'Password1245')
```

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe 'GET #index' do
It is not a `#index` action
```suggestion
  describe '#edit' do
```

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe '#email' do
Do you have an `#email` action?

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +    it 'send valid values' do
Where is it send? To moon?

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe '#password' do
Do you have an `#password` action?

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +    it 'send valid values' do
Rename it

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe '#address' do
Do you have an `#address` action?

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +    it 'returns invalid params' do
> returns invalid params
> redirect to

Try to follow of structure of tests

2021-06-17 11:01 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +    it '#create' do
The same

2021-06-17 11:01 UTC, legendado commented on spec/factories/addresses.rb
> +    trait :billing_address do
```suggestion
    trait :with_billing_address do
```

2021-06-17 11:01 UTC, legendado commented on spec/factories/addresses.rb
> +    trait :shipping_address do
```suggestion
    trait :with_shipping_address do
```

2021-06-17 11:01 UTC, legendado commented on spec/factories/users.rb
> +    factory :user_with_addresses do
Why do you need factory inside factory?
1. Use traits
2. Split it to 2 traits: with shipping and billing addresses

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +      expect(User.where(id: user.id)).not_to exist
It is not a part of feature tests

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'remove account user' do
Rename it
Content of test doesn't match to the test name

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +      User.where(id: user.id)
Remove it

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'update email' do
Rename it

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +      settings_page.privacy_form.update_email(email: user.email)
Try to use another name and check that new email is displayed on the page

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'update password' do
Rename it

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +  context 'when enter billing address' do
```suggestion
  context 'when enter addresses' do
```

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'save billing address' do
```suggestion
    it 'updates billing address' do
```

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'save shipping address' do
```suggestion
    it 'updates shipping address' do
```

2021-06-17 11:01 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +  context 'when enter billing address' do
Also, add tests for failure case

2021-06-17 11:01 UTC, legendado commented on spec/models/address_spec.rb
> +  describe 'validations' do
What about else fields?

2021-06-17 11:01 UTC, legendado commented on spec/models/address_spec.rb
> +RSpec.describe Address do
1. Association tests is absent
2. Format tests is absent
3. Length tests is absent

2021-06-17 11:01 UTC, legendado commented on spec/support/config/host.rb
> +def test_host
Why do you need it?
Remove it

2021-06-17 11:01 UTC, legendado commented on spec/support/pages/home.rb
> +  element :div_danger, 'div.alert.alert-danger'
```suggestion
  element :success_flash_message, '.alert-success'
  element :danger_flash_message, '.alert-danger'
```

2021-06-17 11:01 UTC, legendado commented on spec/support/pages/users/billing_address_page.rb
> +    def input_billing_address(address)
Could we move it to `fill_in_billing_address` method?

2021-06-17 11:01 UTC, legendado commented on spec/support/pages/users/billing_address_page.rb
> +    def input_user_name(address)
Could we move it to `fill_in_billing_address` method?

2021-06-17 11:01 UTC, legendado commented on spec/support/pages/users/billing_address_page.rb
> +    def initialize_billing_address(address)
```suggestion
    def fill_in_billing_address(address)
```

2021-06-17 11:01 UTC, legendado commented on spec/support/pages/users/privacy_form_page.rb
> +      cancel_button.click
Could we choose another name of this element, because of context of method is confused?

2021-06-17 11:01 UTC, legendado commented on spec/support/pages/users/shipping_address_page.rb
> +    def initialize_shipping_address(address)
The same comments as above about billing address

2021-06-17 11:01 UTC, legendado commented on spec/support/pages/users/user_settings.rb
> +    element :flash_success, '.alert.alert-success'
```suggestion
    element :success_flash_,message '.alert-success'
```

2021-06-17 13:16 UTC, skoomer commented on app/controllers/users/registrations_controller.rb
> +    def edit; end
> Why do you need it?

if remove it , when fail feature test and address not edit

2021-06-30 13:43 UTC, OlexandrToloshnyak approved these changes

2021-06-30 13:43 UTC, OlexandrToloshnyak commented on spec/features/users/user_settings_page_spec.rb
> +RSpec.describe Users::UserSettingsPage do
Need failure specs

2021-07-02 08:31 UTC, legendado requested changes

2021-07-02 08:31 UTC, legendado commented on .gitignore
> +/config/credentials/production.key
Remove it

2021-07-02 08:31 UTC, legendado commented on app/controllers/users/registrations_controller.rb
> +    def edit; end
Are you sure about that?

2021-07-02 08:31 UTC, legendado commented on app/views/devise/registrations/edit.html.haml
> +      %a.tab-link{href: "/user/address"}= t('.address')
1. Are you sure that this route is correct?
2. Use `link_to` helper

2021-07-02 08:31 UTC, legendado commented on app/views/devise/registrations/edit.html.haml
> +          = label_tag 'check_Box', t('.confirm')
```suggestion
          = check_box_tag 'check_box', class: 'form-check-input'
          = label_tag 'check_box', t('.confirm')
```

2021-07-02 08:31 UTC, legendado commented on db/migrate/20210517155123_create_addresses.rb
> +      t.string :phone_number
Address model doesn't match to the table
1. Add `null: false` constraints
2. Add `limits` according to the model

2021-07-02 08:31 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +    it 'renders the index template' do
```suggestion
    it 'renders the edit template' do
```

2021-07-02 08:31 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe 'update email' do
Please, reorganise the structure of tests
Example:
```ruby
describe '#action' do
  describe 'success' do
    it 'returns status 200' do
    end
  end

  describe 'failure' do
    it 'returns status 404' do
    end
  end
end

2021-07-02 08:31 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'remove account profile' do
```suggestion
    it 'renders success flash message' do
```

2021-07-02 08:31 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'change email' do
```suggestion
    it 'updates email' do
```

2021-07-02 08:31 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'change password' do
```suggestion
    it 'updates password' do
```

2021-07-02 08:31 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +  context 'when enter addresses' do
```suggestion
  describe 'addresses' do
```

2021-07-02 08:31 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'update billing address' do
```suggestion
    it 'updates billing address' do
```

2021-07-02 08:31 UTC, legendado commented on spec/features/users/user_settings_page_spec.rb
> +    it 'update shipping address' do
```suggestion
    it 'updates shipping address' do
```

2021-07-02 08:31 UTC, legendado commented on spec/models/address_spec.rb
> +  describe 'length address field' do
```suggestion
  describe 'length validations' do
```

2021-07-02 08:31 UTC, legendado commented on spec/models/address_spec.rb
> +  describe 'validations address format' do
```suggestion
  describe 'format validations' do
```

2021-07-02 08:31 UTC, legendado commented on spec/models/address_spec.rb
> +    it 'return country name' do
```suggestion
    it 'returns country name' do
```

2021-07-02 08:31 UTC, legendado commented on spec/support/pages/home.rb
> +  element :email_header, 'a#user-email'
```suggestion
  element :email_header, '#user-email'
```

2021-07-02 08:31 UTC, legendado commented on spec/support/pages/home.rb
>    element :failure_flash_message, 'div.alert.alert-danger'
```suggestion
  element :success_flash_message, '.alert-success'
  element :failure_flash_message, '.alert-danger'
```

2021-07-02 13:31 UTC, legendado requested changes

2021-07-02 13:31 UTC, legendado commented on app/views/devise/registrations/edit.html.haml
> +          = label_tag 'check_Box', t('.confirm')
```suggestion
          = label_tag 'check_box', t('.confirm')
```

2021-07-02 13:31 UTC, legendado commented on app/webpack/js/users.js
> +$(document).on('turbolinks:load', function() {
Use 2 tabs instead of 4

2021-07-02 13:31 UTC, legendado commented on app/webpack/js/users.js
> +    })
```ruby
$('.cancel-account-js').prop('disabled', !$(this).is(':checked'));
```

2021-07-02 13:31 UTC, legendado commented on app/webpack/js/users.js
> +    $('.tabs ul li').click(function () {
Why do you need it?
Is the bootstrap tab component not working?

2021-07-02 13:31 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe '#action' do
Do you have action which is calls `action`?
As I see, from the context of the test, you are describe the `put` action
So call this group of tests as expected
```suggestion
  describe '#put' do
```

2021-07-02 13:31 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe 'update password' do
Move this part of code to the `put` action context according to the success/failure cases

2021-07-02 13:31 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe 'create user address' do
The same

2021-07-02 13:31 UTC, legendado commented on spec/controllers/users/registrations_controller_spec.rb
> +  describe 'update address' do
The same

2021-07-02 13:48 UTC, skoomer commented on app/webpack/js/users.js
> +    $('.tabs ul li').click(function () {
> Is the bootstrap tab component not working?

I tried without, not working

2021-07-04 07:07 UTC, legendado approved these changes

2021-07-04 07:07 UTC, merged